### ISSUE TITLE
'EXTERNAL' isn't a valid option for class 'DeviceType'

### ISSUE THREAD

**Issue by codac** [hahn-th/homematicip-rest-api#496]
Running `home.get_current_state()` results in the error message 'EXTERNAL' isn't a valid option for class 'DeviceType'.
Any hints about how to fix that?

**Comment by hahn-th** [comment]
Update to the latest Version. 
But pls append your config here

**Comment by codac** [comment]
I've updated to the nightly build, but error remains.
Here is my config:
https://gist.github.com/codac/96232e5027f12e5c2e2744b1632a04a9

**Comment by hahn-th** [comment]
This is the Hue Integration, which is fixed a while ago. Update to latest version / use latest sources or remove the Hue devices from your homematic setup.

**Comment by codac** [comment]
@hahn-th
I tried to update via:
`pip install -U homematicip`
and
`pip install -U homematicip --pre`
But the error remains. Is there anything that I'm missing?

**Comment by hahn-th** [comment]
I guess youre code does not use the latest version. Maybe you are using venv? Or a different interpreter? Or maybe you have cloned the sources from github?
